### ISSUE TITLE
PA Check - Chatroom feature complete

### ISSUE THREAD

**Issue by aclee91** [aclee91/Dischat#15]
Chatroom feature should be complete

**Comment by mashuDuek** [comment]
Hey Aarron, 

Looks good. Only a couple small changes. 

When you create a chatroom, you should probably be redirected to it. 

Also, I know that the rest of the CRUD aspects of chatrooms will come once we do channels. 
But the Chatroom name you can display now. 

So once you get those two changes done, let me know and I'll check off on it. 

Mashu

**Comment by aclee91** [comment]
the redirect is complete, i'm working on the component for the title

**Comment by mashuDuek** [comment]
Sounds good. I'll close the issue once that's done.

**Comment by aclee91** [comment]
title component complete, also added in logout button and username

**Comment by mashuDuek** [comment]
Hi Aarron, this looks amazing! 
I'm closing this issue.
